### ISSUE TITLE
Installation issue: survcomp is not available

### ISSUE THREAD

**Issue by bvreede** [mirkosignorelli/pencal_devel#3]
```
ERROR: dependency ‘survcomp’ is not available for package ‘pencal’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/pencal’
Warning messages:
1: package ‘survcomp’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In i.p(...) :
  installation of package ‘/var/folders/35/k2hft7b906g7502vy51zrbz40000gn/T//RtmpQMoEP3/file123a82c22baf2/pencal_1.3.2.tar.gz’ had non-zero exit status
```

My R is version 4.3.1 (2023-06-16).

**Comment by bvreede** [comment]
I had to install `survcomp` manually from [Bioconductor](https://bioconductor.org/packages/release/bioc/html/survcomp.html).

**Comment by bvreede** [comment]
In the issue you link there is this comment: https://github.com/r-lib/devtools/issues/700#issuecomment-235127291 — worth trying?

**Comment by bvreede** [comment]
It solved the problem for me, see my PR (#5). Let's look at this on Friday!

**Comment by mirkosignorelli** [comment]
This is strange, because I tried using the biocViews: trick too and it did not work for me. The only difference seems to be that you uninstalled an extra packag(survival)e that is not a Bioconductor one. To be continued...

**Comment by mirkosignorelli** [comment]
Update: the biocViews: trick does work, as long as installation is from an online repository (whereas dependencies are not sought after when installing from a local tarball). So adding biocViews: to the description solves the issue :)
